name = "engineer-daily-worker"
main = "src/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "KV"
id = "0ea2bc1cbb594d0baa00b5dc05039a90"
preview_id = "b03f18b10c7c41269d6a87b9593f59d0"

[triggers]
crons = [
  "0 * * * *",
  "30 5 * * *"
]

[vars]
ENVIRONMENT = "production"

[dev]
port = 8788

