import type { FeedSource } from "../types";

export const SOURCES: FeedSource[] = [
  { id: "openai-blog",        name: "OpenAI Blog",            url: "https://openai.com/blog/rss.xml",                             category: "AI",                   reputationScore: 0.95, feedType: "rss" },
  { id: "anthropic-blog",     name: "Anthropic Blog",         url: "https://www.anthropic.com/rss.xml",                           category: "AI",                   reputationScore: 0.95, feedType: "rss" },
  { id: "huggingface-blog",   name: "Hugging Face Blog",      url: "https://huggingface.co/blog/feed.xml",                        category: "AI",                   reputationScore: 0.90, feedType: "rss" },
  { id: "google-deepmind",    name: "Google DeepMind",        url: "https://deepmind.google/blog/rss.xml",                        category: "AI",                   reputationScore: 0.92, feedType: "rss" },
  { id: "netflix-tech",       name: "Netflix Tech Blog",      url: "https://netflixtechblog.com/feed",                            category: "Engineering",          reputationScore: 0.92, feedType: "rss" },
  { id: "stripe-blog",        name: "Stripe Engineering",     url: "https://stripe.com/blog/feed/rss",                            category: "Engineering",          reputationScore: 0.94, feedType: "rss" },
  { id: "cloudflare-blog",    name: "Cloudflare Blog",        url: "https://blog.cloudflare.com/rss/",                            category: "Engineering",          reputationScore: 0.90, feedType: "rss" },
  { id: "databricks-blog",    name: "Databricks Blog",        url: "https://www.databricks.com/blog/category/engineering/feed",   category: "Engineering",          reputationScore: 0.88, feedType: "rss" },
  { id: "uber-eng",           name: "Uber Engineering",       url: "https://www.uber.com/en-US/blog/engineering/rss/",            category: "Engineering",          reputationScore: 0.88, feedType: "rss" },
  { id: "discord-blog",       name: "Discord Engineering",    url: "https://discord.com/blog/rss.xml",                            category: "Engineering",          reputationScore: 0.85, feedType: "rss" },
  { id: "aws-blog",           name: "AWS News Blog",          url: "https://aws.amazon.com/blogs/aws/feed/",                      category: "Cloud",                reputationScore: 0.88, feedType: "rss" },
  { id: "gcp-blog",           name: "Google Cloud Blog",      url: "https://cloudblog.withgoogle.com/rss/",                       category: "Cloud",                reputationScore: 0.87, feedType: "rss" },
  { id: "azure-blog",         name: "Azure Blog",             url: "https://azure.microsoft.com/en-us/blog/feed/",                category: "Cloud",                reputationScore: 0.85, feedType: "rss" },
  { id: "mongodb-blog",       name: "MongoDB Blog",           url: "https://www.mongodb.com/blog/rss",                            category: "Databases",            reputationScore: 0.82, feedType: "rss" },
  { id: "postgres-news",      name: "PostgreSQL News",        url: "https://www.postgresql.org/news.rss",                         category: "Databases",            reputationScore: 0.86, feedType: "rss" },
  { id: "martin-fowler",      name: "Martin Fowler",          url: "https://martinfowler.com/feed.atom",                          category: "Distributed Systems",  reputationScore: 0.94, feedType: "atom" },
  { id: "high-scalability",   name: "High Scalability",       url: "http://feeds.feedburner.com/HighScalability",                 category: "Distributed Systems",  reputationScore: 0.85, feedType: "rss" },
  { id: "infoq",              name: "InfoQ",                  url: "https://feed.infoq.com/",                                     category: "Distributed Systems",  reputationScore: 0.84, feedType: "rss" },
  { id: "github-blog",        name: "GitHub Blog",            url: "https://github.blog/feed/",                                   category: "Open Source",          reputationScore: 0.88, feedType: "rss" },
  { id: "hn-best",            name: "Hacker News Best",       url: "https://hnrss.org/best",                                      category: "Open Source",          reputationScore: 0.80, feedType: "rss" },
  { id: "a16z",               name: "a16z Blog",              url: "https://a16z.com/feed/",                                      category: "Startups",             reputationScore: 0.85, feedType: "rss" },
  { id: "first-round",        name: "First Round Review",     url: "https://review.firstround.com/feed.xml",                      category: "Startups",             reputationScore: 0.87, feedType: "rss" },
  { id: "trail-of-bits",      name: "Trail of Bits Blog",     url: "https://blog.trailofbits.com/rss",                            category: "Security",             reputationScore: 0.90, feedType: "rss" },
  { id: "google-security",    name: "Google Security Blog",   url: "https://security.googleblog.com/feeds/posts/default",         category: "Security",             reputationScore: 0.89, feedType: "atom" },
  { id: "papers-with-code",   name: "Papers With Code",       url: "https://paperswithcode.com/rss.xml",                          category: "Research",             reputationScore: 0.88, feedType: "rss" },
  { id: "google-research",    name: "Google Research Blog",   url: "https://research.google/blog/rss/",                           category: "Research",             reputationScore: 0.90, feedType: "rss" },
];
